# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - miztonKm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Create .env file
        run: |
          echo "REACT_APP_PASS=${{ secrets.REACT_APP_PASS }}" > .env
          # Añade aquí más variables de entorno si es necesario, por ejemplo:
          # echo "REACT_APP_ANOTHER_SECRET=${{ secrets.REACT_APP_ANOTHER_SECRET }}" >> .env
        env:
          REACT_APP_PASS: ${{ secrets.REACT_APP_PASS }}

      - name: npm install, build, and test
        run: |
          npm install
          CI=false npm run build --if-present
      # npm test --if-present

      # Este paso ya no es necesario ya que ahora solo vamos a subir el build
      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r

      - name: Upload build directory as artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./build/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build directory from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./build

      # Este paso ya no es necesario ya que el artefacto es directamente el build
      # - name: Unzip artifact for deployment
      #   run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "miztonKm"
          slot-name: "Production"
          package: ./build
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1EC7A1B47F594E86AB38BCEB3C9A55E7 }}

  #     - name: npm install, build, and test
  #       run: |
  #         npm install
  #         npm run build --if-present
  #         npm run test --if-present

  #     - name: Zip artifact for deployment
  #       run: zip release.zip ./* -r

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: node-app
  #         path: release.zip

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: node-app

  #     - name: Unzip artifact for deployment
  #       run: unzip release.zip

  #     - name: 'Deploy to Azure Web App'
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'miztonKm'
  #         slot-name: 'Production'
  #         package: ./build
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1EC7A1B47F594E86AB38BCEB3C9A55E7 }}
